# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb98f58bc1c7e753aca116379083434ec930eb21b2b492edb2f182cffa1313437bf308473201674e15073da2ea6d5bb3c2f83a0806edeb1e3281881c1c3ba899

test:
  secret_key_base: 012262c960bcdb4c4d897cbb3a45e303382ee2cee942103b8561ede75395cc3121cb45daed18e122fba15d7e2f0c78f575a1ade1b6ca007686e2d627cba94553

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
